In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

df = pd.read_csv("../data/raw/DataSet.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (17880, 18)

In [2]:
df.head()

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,in_balanced_dataset
0,Marketing Intern,"US, NY, New York",Marketing,NaN,"<h3>We're Food52, and we've created a groundbr...","<p>Food52, a fast-growing, James Beard Award-w...",<ul>\r\n<li>Experience with content management...,NaN,f,t,f,Other,Internship,NaN,NaN,Marketing,f,f
1,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"<h3>90 Seconds, the worlds Cloud Video Product...",<p>Organised - Focused - Vibrant - Awesome!<br...,<p><b>What we expect from you:</b></p>\r\n<p>Y...,<h3><b>What you will get from us</b></h3>\r\n<...,f,t,f,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,f,f
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,<h3></h3>\r\n<p>Valor Services provides Workfo...,"<p>Our client, located in Houston, is actively...",<ul>\r\n<li>Implement pre-commissioning and co...,NaN,f,t,f,NaN,NaN,NaN,NaN,NaN,f,f
3,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,<p>Our passion for improving quality of life t...,<p><b>THE COMPANY: ESRI – Environmental System...,<ul>\r\n<li>\r\n<b>EDUCATION: </b>Bachelor’s o...,<p>Our culture is anything but corporate—we ha...,f,t,f,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,f,f
4,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,<p>SpotSource Solutions LLC is a Global Human ...,<p><b>JOB TITLE:</b> Itemization Review Manage...,<p><b>QUALIFICATIONS:</b></p>\r\n<ul>\r\n<li>R...,<p>Full Benefits Offered</p>,f,t,t,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,f,f

In [3]:
df.columns.tolist()

['title',
 'location',
 'department',
 'salary_range',
 'company_profile',
 'description',
 'requirements',
 'benefits',
 'telecommuting',
 'has_company_logo',
 'has_questions',
 'employment_type',
 'required_experience',
 'required_education',
 'industry',
 'function',
 'fraudulent',
 'in_balanced_dataset']

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   title                17880 non-null  str
 1   location             17534 non-null  str
 2   department           6333 non-null   str
 3   salary_range         2868 non-null   str
 4   company_profile      14572 non-null  str
 5   description          17880 non-null  str
 6   requirements         15191 non-null  str
 7   benefits             10684 non-null  str
 8   telecommuting        17880 non-null  str
 9   has_company_logo     17880 non-null  str
 10  has_questions        17880 non-null  str
 11  employment_type      14409 non-null  str
 12  required_experience  10830 non-null  str
 13  required_education   9775 non-null   str
 14  industry             12977 non-null  str
 15  function             11425 non-null  str
 16  fraudulent           17880 non-null  str
 17  in_balanced_dataset  17880 non-null  str
dtypes: str(18)
memory usage: 2.5 MB

In [5]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

missing

salary_range           15012
department             11547
required_education      8105
benefits                7196
required_experience     7050
function                6455
industry                4903
employment_type         3471
company_profile         3308
requirements            2689
location                 346
dtype: int64

In [6]:
df["fraudulent"].value_counts()

fraudulent
f    17014
t      866
Name: count, dtype: int64

In [7]:
df["fraudulent"].value_counts(normalize=True) * 100

fraudulent
f    95.1566
t     4.8434
Name: proportion, dtype: float64

In [8]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 235

Investigate in_balanced_dataset

In [9]:
df["in_balanced_dataset"].value_counts(dropna=False)

in_balanced_dataset
f    16980
t      900
Name: count, dtype: int64

In [10]:
pd.crosstab(
    df["in_balanced_dataset"],
    df["fraudulent"],
    margins=True
)

fraudulent               f    t    All
in_balanced_dataset
f                    16564  416  16980
t                      450  450    900
All                  17014  866  17880

In [11]:
duplicate_rows = df[df.duplicated(keep=False)].sort_values(
    by=df.columns.tolist()
)

print("Total rows involved in duplicates:", len(duplicate_rows))

Total rows involved in duplicates: 439

In [12]:
duplicate_rows["fraudulent"].value_counts()

fraudulent
f    425
t     14
Name: count, dtype: int64

In [13]:
duplicate_groups = (
    duplicate_rows
    .groupby(df.columns.tolist(), dropna=False)["fraudulent"]
    .nunique()
)

print("Duplicate groups with conflicting labels:",
      (duplicate_groups > 1).sum())

Duplicate groups with conflicting labels: 0